---
- name: Manage NextDNS configuration on OpenWRT or OPNsense
  hosts: "{{ target_hosts }}"
  become: yes
  gather_facts: no
  vars:
    mac_address: "{{ mac_address }}"

  tasks:
    - name: Check if /etc/config/nextdns exists (OpenWRT check)
      ansible.builtin.raw: "test -f /etc/config/nextdns && echo 'exists' || echo 'not_found'"
      register: nextdns_file_check

    - name: Set OS type based on file presence
      set_fact:
        os_type: "{{ 'openwrt' if 'exists' in nextdns_file_check.stdout else 'opnsense' }}"

    # OpenWRT-specific tasks
    - name: Remove MAC address from NextDNS configuration (OpenWRT)
      ansible.builtin.raw: "sed -i '/list config {{ mac_address }}/d' /etc/config/nextdns"
      when: os_type == 'openwrt'
      register: removal_result_openwrt

    - name: Restart NextDNS service (OpenWRT)
      ansible.builtin.raw: "nextdns restart"
      when: os_type == 'openwrt' and removal_result_openwrt.changed
      register: restart_result_openwrt

    - name: Check NextDNS status (OpenWRT)
      ansible.builtin.raw: "nextdns status"
      when: os_type == 'openwrt' and restart_result_openwrt.changed
      register: status_result_openwrt

    - name: Verify NextDNS is running (OpenWRT)
      ansible.builtin.fail:
        msg: "NextDNS is not running on OpenWRT! Status: {{ status_result_openwrt.stdout }}"
      when: os_type == 'openwrt' and status_result_openwrt.stdout.strip() != 'running'

    # OPNsense-specific tasks
    - name: Remove MAC address from NextDNS configuration (OPNsense)
      ansible.builtin.lineinfile:
        path: "/usr/local/etc/nextdns.conf"
        state: absent
        regexp: "{{ mac_address }}"
      when: os_type == 'opnsense'
      register: removal_result_opnsense

    - name: Restart NextDNS service (OPNsense)
      ansible.builtin.service:
        name: nextdns
        state: restarted
      when: os_type == 'opnsense' and removal_result_opnsense.changed

    # Summary of actions
    - name: Summary of actions
      ansible.builtin.debug:
        msg: >-
          OS Type: {{ os_type }}
          - OpenWRT: 
            Removal Result: {{ removal_result_openwrt.changed | default('N/A') }}
            Restart Result: {{ restart_result_openwrt.changed | default('N/A') }}
          - OPNsense:
            Removal Result: {{ removal_result_opnsense.changed | default('N/A') }}
