---
- name: Delete MAC address from OPNsense configuration
  hosts: {{ target_hosts }}
  become: yes
  vars:
    mac_address: "{{ mac_address }}"  

  tasks:
    - name: Ensure the specified MAC address line is removed
      lineinfile:
        path: "/usr/local/etc/nextdns.conf"
        state: absent
        regexp: "{{ mac_address }}"
      when: mac_address is defined
      
    - name: Restart NextDNS to apply changes if profile was added or updated
      ansible.builtin.service:
        name: nextdns
        state: restarted
      when: profile_update.changed
