---
- name: Delete MAC address from OPNsense configuration
  hosts: "{{ target_hosts }}"  # Make sure to define this when running the playbook or replace it with a specific group
  become: yes
  vars:
    mac_address: "{{ mac_address }}"  

  tasks:
    - name: Ensure the specified MAC address line is removed
      lineinfile:
        path: "/usr/local/etc/nextdns.conf"
        state: absent
        regexp: "{{ mac_address }}"
      when: mac_address is defined
      register: mac_line_removal  # Register the result to use in the next task

    - name: Restart NextDNS to apply changes if MAC address line was removed
      ansible.builtin.service:
        name: nextdns
        state: restarted
      when: mac_line_removal.changed  # Check if the previous task made any changes
