- name: Get dhcp client
  hosts: "{{ target_hosts }}"
  gather_facts: no
  tasks:
    - name: Read file using raw
      raw: "cat /tmp/dhcp.leases"
      register: file_contents

    - name: Show file contents
      debug:
        msg: "{{ file_contents.stdout }}"
