- name: Get DHCP clients
  hosts: "{{ target_hosts }}"
  gather_facts: no
  become: yes
  tasks:
    - name: Check if device is OpenWRT or OPNsense
      raw: test -f /usr/local/etc/opnsense-update.conf && echo "opnsense" || (test -f /etc/openwrt_version && echo "openwrt" || echo "unknown")
      register: fw_check
      changed_when: false
      ignore_errors: yes

    - name: Extract firewall type
      set_fact:
        fw_type: "{{ fw_check.stdout | default('unknown') }}"

    - name: Read DHCP lease file
      raw: "cat {{ '/tmp/dhcp.leases' if fw_type == 'openwrt' else '/var/dhcpd/var/db/dhcpd.leases' if fw_type == 'opnsense' else '/dev/null' }}"
      register: file_contents
      when: fw_type in ['openwrt', 'opnsense']
      changed_when: false

    - name: Return cleaned DHCP leases
      debug:
        msg: "{{ file_contents.stdout_lines | select('search', '.') | list }}"
      when: file_contents.stdout is defined
