- name: Parse nextdns.conf for MAC address profile mappings
  hosts: "{{ target_hosts }}"
  become: yes
  tasks:
    - name: Read nextdns.conf file
      ansible.builtin.slurp:
        src: /usr/local/etc/nextdns.conf
      register: nextdns_conf_raw

    - name: Decode and split nextdns.conf contents
      set_fact:
        nextdns_conf_content: "{{ nextdns_conf_raw.content | b64decode | split('\n') }}"

    - name: Extract MAC addresses with assigned profiles
      set_fact:
        mac_profiles: "{{ nextdns_conf_content | select('search', '^profile\\s+[0-9A-Fa-f:]+=\\w+') 
                         | map('regex_replace', '^profile\\s+([0-9A-Fa-f:]+)=(\\w+)', '{\"mac\": \"\\1\", \"profile\": \"\\2\"}')
                         | map('from_json')
                         | list }}"

    - name: Display MAC address and profile mappings
      ansible.builtin.debug:
        msg: "MAC and profile pairs: {{ mac_profiles }}"
