- name: Parse nextdns.conf for MAC address and profile mappings
  hosts: "{{ target_hosts }}"
  become: yes
  tasks:
    - name: Read nextdns.conf file
      ansible.builtin.slurp:
        src: /usr/local/etc/nextdns.conf
      register: nextdns_conf_raw

    - name: Decode and split nextdns.conf contents
      set_fact:
        nextdns_conf_content: "{{ nextdns_conf_raw.content | b64decode | splitlines }}"

    - name: Extract MAC addresses with profiles
      set_fact:
        mac_profiles: "{{ nextdns_conf_content | regex_findall('^profile ([0-9a-fA-F:]+)=(\\w+)') | map('regex_replace', '^profile ([0-9a-fA-F:]+)=(\\w+)', '\\1: \\2') | list }}"

    - name: Display MAC address and profile mappings
      ansible.builtin.debug:
        msg: "MAC and profile pairs: {{ mac_profiles }}"
