- name: Parse nextdns.conf for MAC address profile mappings
  hosts: "{{ target_hosts }}"
  become: yes
  tasks:
    - name: Read nextdns.conf file
      ansible.builtin.slurp:
        src: /usr/local/etc/nextdns.conf
      register: nextdns_conf_raw

    - name: Decode and split nextdns.conf contents
      set_fact:
        nextdns_conf_content: "{{ nextdns_conf_raw.content | b64decode | split('\n') }}"

    - name: Filter all profile lines
      set_fact:
        profile_lines: "{{ nextdns_conf_content | select('search', '^profile\\s+') | list }}"

    - name: Debug all profile lines for inspection
      ansible.builtin.debug:
        var: profile_lines

    - name: Extract MAC addresses, profiles, and optional device names
      set_fact:
        mac_profiles: "{{ profile_lines 
                         | map('regex_replace', '^profile\\s+([0-9A-Fa-f:]+)=(\\w+)(?:\\s+#(.*))?', '{\"mac\": \"\\1\", \"profile\": \"\\2\", \"device_name\": \"\\3\"}')
                         | map('from_json')
                         | list }}"

    - name: Display MAC address, profile, and device name mappings
      ansible.builtin.debug:
        msg: |
          MAC, profile, and device name pairs:
          {% for item in mac_profiles %}
          'mac': '{{ item.mac }}', 'profile': '{{ item.profile }}'{% if item.device_name %}, 'device_name': '{{ item.device_name }}'{% endif %}
          {% endfor %}
