---
- name: Parse NextDNS config
  hosts: "{{ target_hosts }}"
  gather_facts: no
  tasks:
    - name: Read the NextDNS config file
      slurp:
        src: /usr/local/etc/nextdns.conf
      register: nextdns_conf

    - name: Decode NextDNS config content
      set_fact:
        nextdns_content: "{{ nextdns_conf.content | b64decode }}"

    - name: Parse default profile
      set_fact:
        default_profile: "{{ nextdns_content | regex_search('(?m)^profile\\s+([a-zA-Z0-9]+)', '\\1') | first }}"

    - name: Parse devices and profiles
      set_fact:
        devices: "{{ nextdns_content | regex_findall('(?m)^//device\\s+(?P<mac>[a-fA-F0-9:]+)\\s+(?P<name>.+?),\\s+profile\\s+\\g<mac>=(?P<profile>[a-zA-Z0-9]+)') }}"

    - name: Assemble output in JSON
      set_fact:
        parsed_data:
          default_profile: "{{ default_profile }}"
          devices: "{{ devices }}"

    - name: Print parsed data as JSON
      debug:
        var: parsed_data | to_nice_json
      when: parsed_data is defined
