---
- name: Parse NextDNS config
  hosts: "{{ target_devices }}"
  gather_facts: no
  tasks:
    - name: Read the NextDNS config file
      slurp:
        src: /usr/local/etc/nextdns.conf
      register: nextdns_conf

    - name: Decode NextDNS config content
      set_fact:
        nextdns_content: "{{ nextdns_conf.content | b64decode }}"

    - name: Parse default profile
      set_fact:
        default_profile: "{{ nextdns_content | regex_search('^profile\\s+([a-zA-Z0-9]+)', '\\1') }}"

    - name: Parse devices and profiles
      set_fact:
        devices: "{{ nextdns_content | regex_findall('\\/\\/device\\s+([a-fA-F0-9:]+)\\s+(.+?)\\",\\s+profile\\s+\\1=([a-zA-Z0-9]+)', '\\1', '\\2', '\\3') | map('list', ['device_mac_address', 'device_name', 'device_assigned_profile']) }}"

    - name: Assemble output in JSON
      set_fact:
        parsed_data: >
          {{
            {
              "default_profile": default_profile,
              "devices": devices | map('dict')
            }
          }}

    - name: Print parsed data as JSON
      debug:
        var: parsed_data
      when: parsed_data is defined
