- name: Reboot firewall
  hosts: "{{ target_hosts }}"
  become: no
  gather_facts: no
  tasks:
    - name: Reboot firewall
      ansible.builtin.shell: configctl system reboot
      async: 1
      poll: 0

    - name: Wait for firewalls to come back
      ansible.builtin.wait_for_connection:
        delay: 30
        timeout: 300
