- name: Reboot firewall
  hosts: "{{ target_hosts }}"
  become: no
  gather_facts: no
  tasks:
    - name: Get system info
      raw: cat /etc/openwrt_version || cat /usr/local/etc/opnsense-update.conf || echo "unknown"
      register: system_check
      ignore_errors: yes
      
    - name: Set firewall type fact
      ansible.builtin.set_fact:
        firewall_type: >-
          {% if '/usr/local/etc/opnsense-update.conf' in system_check.stdout %}opnsense
          {% elif '/etc/openwrt_version' in system_check.stdout %}ddwrt
          {% else %}unknown{% endif %}
          
    - name: Show detected firewall
      ansible.builtin.debug:
        msg: "Detected firewall type: {{ firewall_type }}"
        msg: "stdout: {{ system_check.stdout }}"
        
    - name: Wait for reboot
      ansible.builtin.wait_for_connection:
        delay: 30
        timeout: 300
      when: firewall_type != "unknown"
