- name: Reboot firewall
  hosts: "{{ target_hosts }}"
  become: no
  gather_facts: no
  tasks:
    - name: Reboot firewall
      ansible.builtin.shell: "shutdown -r now"
      async: 1
      poll: 0
      ignore_errors: yes
      changed_when: true
      check_mode: no

    - name: Wait for firewall to come back online
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        delay: 10
        timeout: 300
      delegate_to: localhost
