- name: Reboot firewall
  hosts: "{{ target_hosts }}"
  become: yes
  gather_facts: no
  tasks:
    - name: Reboot firewall
      ansible.builtin.command: /sbin/reboot
      async: 1
      poll: 0
      ignore_errors: yes
      changed_when: false

    - name: Wait for firewall to come back online
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        delay: 10
        timeout: 300
      delegate_to: localhost
