- name: Reboot firewall
  hosts: "{{ target_hosts }}"
  become: no
  gather_facts: no
  tasks:
    - name: Check if OPNsense
      raw: test -f /usr/local/etc/opnsense-update.conf && echo "opnsense" || (test -f /etc/openwrt_version && echo "openwrt" || echo "unknown")
      register: fw_check
      ignore_errors: yes

    - name: Reboot OPNsense
      raw: configctl system reboot
      when: fw_check.stdout_lines[0] == "opnsense"

    - name: Reboot GLiNet/OpenWRT
      raw: /sbin/poweroff -r -f
      when: fw_check.stdout_lines[0] == "openwrt"
