- name: Reboot firewall
  hosts: "{{ target_hosts }}"
  become: no
  gather_facts: no
  tasks:
    - name: Check if OPNsense
      raw: test -f /usr/local/etc/opnsense-update.conf && echo "opnsense" || (test -f /etc/openwrt_version && echo "openwrt" || echo "unknown")
      register: fw_check
      ignore_errors: yes

    - name: Show detected firewall
      ansible.builtin.debug:
        msg: "fw_check.stdout_lines[0]"
