- name: Update NextDNS with MAC address profile
  hosts: "{{ target_hosts }}"
  become: yes
  gather_facts: no
  vars:
    mac_address: "{{ mac_address }}"  # Replace with the desired MAC address or pass as an extra var
    profile_id: "{{ profile_id }}"    # The profile to assign to the MAC address
    device_name: "{{ device_name }}"  # Familiar name to identify the device

  tasks:
    - name: Convert MAC address hyphens to colons using Jinja2
      set_fact:
        converted_mac_address: "{{ mac_address | regex_replace('-', ':') }}"
        
    - name: Validate the final MAC address format
      fail:
        msg: "MAC address is not valid. Expected format is aa:bb:cc:dd:ee:ff."
      when: not converted_mac_address is match('^[0-9A-Fa-f]{2}(:[0-9A-Fa-f]{2}){5}$')
        
    - name: Validate profile_id format
      ansible.builtin.assert:
        that:
          - profile_id is defined
          - profile_id is match('^[A-Za-z0-9]+$')
        fail_msg: "profile_id '{{ profile_id }}' is invalid. It must contain only letters and numbers, with no spaces or special characters."
        success_msg: "profile_id '{{ profile_id }}' is valid."

    - name: Clean device name by removing unwanted characters
      set_fact:
        cleaned_device_name: "{{ device_name | regex_replace('[^A-Za-z0-9 ]', '') }}"

    - name: Add device to NextDNS configuration
      ansible.builtin.raw: "nextdns config set -config {{ converted_mac_address }}={{ profile_id }}"
      register: add_device_result

    - name: Check if device was added or updated
      ansible.builtin.debug:
        msg: "{{ add_device_result.stdout }}"
      when: "'updated' in add_device_result.stdout or 'added' in add_device_result.stdout"

    - name: Restart NextDNS to apply changes
      ansible.builtin.raw: "nextdns restart"
      when: add_device_result.changed

    - name: Summary of actions
      ansible.builtin.debug:
        msg: >-
          Device {{ cleaned_device_name }} with MAC address {{ converted_mac_address }}
          was successfully {{ 'added/updated' if add_device_result.changed else 'verified' }}
          under profile ID {{ profile_id }}.
